CC=g++
DEP=PropertyThing.cpp 
DEP+=Property.cpp 
DEP+=Tester.cpp
DEP+=SimpleProperty.cpp

SetDEP=Set.cpp
SetDEP+=TesterSet.cpp

PropertyTester:
	$(CC)  -o Tester $(DEP)

Set:
	$(CC) -o TesterSet $(SetDEP)